### ISSUE TITLE
Where can we find the PCB?

### ISSUE THREAD

**Issue by julientaq** [unit-cell/toes#1]
Hi there
amazing project!
Do you have any plan to make those pcb available?

Thanks!

**Comment by markelmart** [comment]
Hey Julien, thanks for the kind words! The PCB files are on the github repo
if that's what you meant. I also have some PCBs left from my first order, I
have been sending them out for 80 SEK + shipping if you're interested.

Best,
Markel

**Comment by julientaq** [comment]
That’s exactly what i had in mind :)

i’ll be happy to get a couple of pcb. i’m in france, so i don’t know how much the shipping would be. (but i’m all up for that)

Also, i believe that we need a way to communicate outside of github :)

**Comment by markelmart** [comment]
Great! Just checked and it seems the shipping would be 130 SEK. Let me know
if it sounds reasonable, and if you give me your address I can post them
asap!

Cheers,
Markel

**Comment by julientaq** [comment]
We’re good! 
How can i send you my address and the money?
I don’t really trust github to be the best place for that :)

**Comment by markelmart** [comment]
Right, did't even notice this was a github issue! I was following on my
email. You can email me your address at markelmc92 [at] gmail.com, we can
continue communicating there!
